### ISSUE TITLE
Publications

### ISSUE THREAD

**Issue by kalampokis** [OpenGovIntelligence/opengovintelligence.github.io#3]
Add the following publications
- E. Kalampokis, E. Tambouris, K. Tarabanis (2016) Linked Open Cube Analytics Systems: Potential and Challenges IEEE Intelligent Systems, Vol. 31, No.5, pp.89-92 http://dx.doi.org/10.1109/MIS.2016.82 
- A. Karamanou, E. Kalampokis, E. Tambouris, K. Tarabanis (2016) Linked data cubes: Research results so far, SemStats2016 in conjuction with the 15th International Semantic Web Conference (ISWC2016), 17-21 October 2016, Kobe, Japan, CEUR-WS 
- E. Tambouris, M. Janssen, E. Kalampokis, B. Roberts, P. Hermans, J. Whyte, T. Alcorn, K. Tarabanis (2016) Open Statistical Data: Potential and Challenges, Scholl, H. et al. (Eds.): Electronic Government and Electronic Participation, pp. 407-408, IOS Press  http://doi.org/10.3233/978-1-61499-670-5-407

In the  "Open Statistics: The Rise of a new Era for Open Data?" replace the pdf with the doi http://dx.doi.org/10.1007/978-3-319-44421-5_3

**Comment by RickMoynihan** [comment]
Hi Evangelos,

Do you really want us to replace the download links with DOI's, or just add the DOI's as well?  

Happy to do either but I think it's better to keep a download link if we can, unless the publications are subject to copyright issues with the journal.

**Comment by RickMoynihan** [comment]
Oh, also is it possible to include the abstracts for these papers in the issue for us, so we can retain the same format as is on the site already?  It makes the job easier if we don't have to chase everything down.

**Comment by kalampokis** [comment]
Ok you can keep both links.

**Comment by ghost** [comment]
ive found abstracts for the two with dois but not for _Linked data cubes: Research results so far_ - so if you could post that, that would be great

**Comment by kalampokis** [comment]
Linked data cubes: Research results so far:
During the last years a growing body of literature studied Linked Data Cubes. The objective of this paper is to accumulate this body of knowledge and provide a preliminary analysis of the research re- sults in the area so far. Towards this end, we systematically reviewed the scientific literature to identify relevant studies. These studies were anal- ysed and synthesised in the form of a proposed conceptual framework, which was thereafter applied to further analyse this literature, hence gaining new insights into the field. The framework comprises three di- mensions, namely category of contribution, step of data analysis, and application area. The application of the framework resulted in interest- ing findings. For example, the majority of the contributions that focus on publishing linked data cubes are cases while the majority of the ex- ploitation contributions are software tools. Moreover, integration of data cubes remains largely unexamined in the literature. This paper, however, does not present the final results of the analysis of the literature as this is still an ongoing activity.

**Comment by ghost** [comment]
https://github.com/OpenGovIntelligence/opengovintelligence.github.io/commit/9b6ef16a3c5d664c36800fa30bfa03760abf7038

**Comment by RickMoynihan** [comment]
@kalampokis Done & deployed.

**Comment by RickMoynihan** [comment]
http://www.opengovintelligence.eu/thinking.html
