### ISSUE TITLE
Deliverables

### ISSUE THREAD

**Issue by kalampokis** [OpenGovIntelligence/opengovintelligence.github.io#4]
Upload all the *public* deliverables in the website. The final versions (pdf) of the deliverables can be found in the google drive /Important/Final Deliverables

**Comment by RickMoynihan** [comment]
Cool I suggest we serve them from the Google Drive, otherwise we'll need to copy them all into GitHub, and then update them if they're ever revised.

Also do you want us to put these documents on the website now, or on a specific date?

**Comment by kalampokis** [comment]
I would propose to add them now. If you think it is better to add them from Google Drive then it is ok.

In general we need to send the website to the commission today so we need to put some content today.

**Comment by RickMoynihan** [comment]
@kalampokis Great if you can share all the deliverable documents from google drive and paste the links to them in this issue we'll add them to the website.

Be warned though if the filenames or folders change on google drive the links may break, if there's a risk of this I'd suggest you copy the documents themselves directly into this github repo, and issue a pull request for us then we can link them to the website.  If you decide to go with this option I'd suggest putting the files in a directory at the root of the repository called `/downloads/deliverables`

**Comment by RickMoynihan** [comment]
@kalampokis Is it possible for you to create a pull request with the documents copied into the github repo under `/donwloads/deliverables`?

I'd rather not change the share settings for the documents as if I change the share settings people won't be able to edit the documents on the google drive anymore.  

I also don't have google drive installed as I don't have enough free disk space to handle the automatic syncing.

**Comment by RickMoynihan** [comment]
Ok @kalampokis as you've not got back to me, I've downloaded all the documents and copied them into github for you and linked them on the website on a [new deliverables page](http://www.opengovintelligence.eu/deliverables.html).

In the future it would be good if you could issue PR's to help with changes like this.  

We're happy for you to make copy changes to markdown pages or even the html pages if you need to and then issue a PR; even uploading or copying files over from the google drive into the `/downloads` directory will help make this process smoother for everyone.

Feel free to ask questions if you're not too sure of how things are setup either.

Let me know if there are any further issues with the website.
